name: Smoke Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version

      - name: Test api module
        run: go test -count=1 -timeout=20m ./...
        working-directory: api

      - name: Test structs and scheduler
        run: go test -count=1 -timeout=20m ./nomad/structs/... ./scheduler/...
